### 预发布环境配置
server:
    ## 端口号
    port: 8082
    ## 访问路径
    servlet:
      context-path: /springboot-ssm

spring:
    ## MySQL数据源
    datasource:
        drive-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        url: jdbc:mysql://127.0.0.1:3306/user?characterEncoding=utf-8&useSSL=false
    jpa:
        show-sql: true
    ## 页面模板
    thymeleaf:
            cache : false
            prefix: classpath:/views/
            suffix: .html
            encoding: UTF-8
            mode: LEGACYHTML5
            servlet:
              content-type: text/html
    ## 邮件支持
    mail:
      host: smtp.qq.com
      protocol: smtp
      default-encoding: UTF-8
      username: pxxxxx@163.com
      password: xxxaasdddxfdcc
      smtp:
        timeout: 15000
        auth: true
        starttls:
          enable: true
          required: true
      defaultEncoding: UTF-8